### ISSUE TITLE
Falsche Links im Header auf der Watchseite

### ISSUE THREAD

**Issue by LeXonJe** [Bergflix/main-website#3]
Die Links auf der Watchseite führen zu /watch/movies, etc. Dadurch, dass das ungültige Links sind, wird man ja somit automatisch auf die Homeseite zurück geleitet, obwohl man z. B. "Filme" angeklickt hat.
Aufgefallen ist mir das bei der gerade laufenden Instanz (Stand: 11.09., 15 Uhr) auf [dev.bergflix.de](https://dev.bergflix.de/).

![wrong_links](https://user-images.githubusercontent.com/30697846/92932483-4671b800-f445-11ea-92fd-f95ec778d973.png)

_Der Bug wäre sowieso bald aufgefallen, aber darauf hinzuweisen schadet nicht. :D_

**Comment by RyanFlm** [comment]
Ah danke. Da hab ich ein "/" zu viel weg gemacht.
