### ISSUE TITLE
"The Taxi Driver" Error Beim abspielen

### ISSUE THREAD

**Issue by dasYemi** [Bergflix/main-website#4]
Hallo.
Beim abspielen von "The Taxi Driver" wird mir dieser Error angezeigt: An error occurred. Please try again later. (Playback ID: YReYfFmtenLQs27K).

**Comment by 6lyxt** [comment]
Hej! Die /watch Seiten wurden noch nicht eingerichtet, und werden demnächst fertig gestellt. Dann sollten Serien ebenfalls funktionieren!
